# Generated by Django 4.2.7 on 2025-12-26 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="staff member",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinics",
                to=settings.AUTH_USER_MODEL,
                verbose_name="doctor/owner",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("staff", "clinic")},
        ),
    ]
