# Generated by Django 5.2 on 2026-01-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="is_accepting_new_patients",
            field=models.BooleanField(
                default=True, verbose_name="accepting new patients"
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="latitude",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="longitude",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="slot_duration",
            field=models.IntegerField(
                default=30,
                help_text="Appointment slot duration in minutes",
                verbose_name="slot duration (minutes)",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="working_hours",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Working hours per day, e.g. {"sunday": {"open": "09:00", "close": "17:00"}, "friday": null}',
                verbose_name="working hours",
            ),
        ),
    ]
