# Generated by Django 5.2 on 2026-01-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clinics",
            "0003_clinic_description_clinic_is_accepting_new_patients_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="is_open",
            field=models.BooleanField(
                default=True,
                help_text="Quick toggle for clinic availability",
                verbose_name="is open",
            ),
        ),
    ]
