# Generated by Django 5.2 on 2026-01-03 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0004_clinic_is_open"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.city",
                verbose_name="city",
            ),
        ),
    ]
