# Generated by Django 5.2 on 2025-12-31 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="blood type"
                    ),
                ),
                ("allergies", models.TextField(blank=True, verbose_name="allergies")),
                (
                    "medical_history",
                    models.TextField(blank=True, verbose_name="medical history"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="patient user",
                    ),
                ),
            ],
            options={
                "verbose_name": "patient profile",
                "verbose_name_plural": "patient profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Pregnancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lmp",
                    models.DateField(
                        blank=True, null=True, verbose_name="last menstrual period"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="due date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("delivered", "Delivered"),
                            ("miscarriage", "Miscarriage"),
                            ("ectopic", "Ectopic"),
                            ("stillbirth", "Stillbirth"),
                        ],
                        default="ongoing",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_high_risk",
                    models.BooleanField(
                        default=False, verbose_name="high risk pregnancy"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pregnancies",
                        to="clinics.clinic",
                        verbose_name="created by clinic",
                    ),
                ),
                (
                    "patient_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pregnancies",
                        to="users.patientprofile",
                        verbose_name="patient profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "pregnancy",
                "verbose_name_plural": "pregnancies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Baby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="name"),
                ),
                (
                    "gender",
                    models.CharField(blank=True, max_length=20, verbose_name="gender"),
                ),
                (
                    "birth_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="birth date"
                    ),
                ),
                (
                    "birth_weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="birth weight (kg)"
                    ),
                ),
                (
                    "birth_length",
                    models.FloatField(
                        blank=True, null=True, verbose_name="birth length (cm)"
                    ),
                ),
                (
                    "apgar_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="APGAR score"
                    ),
                ),
                ("is_born", models.BooleanField(default=False, verbose_name="is born")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pregnancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="babies",
                        to="users.pregnancy",
                        verbose_name="pregnancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "baby",
                "verbose_name_plural": "babies",
                "ordering": ["-created_at"],
            },
        ),
    ]
