# Generated by Django 5.2 on 2026-01-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_migrate_existing_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="phone number"
                    ),
                ),
                ("otp_code", models.CharField(max_length=6, verbose_name="OTP code")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                ("is_used", models.BooleanField(default=False, verbose_name="is used")),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, verbose_name="verification attempts"
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP verification",
                "verbose_name_plural": "OTP verifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Unique phone number for OTP authentication",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="phone number",
            ),
        ),
    ]
