# Generated by Django 5.2 on 2026-01-11 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="file name")),
                (
                    "file_id",
                    models.CharField(max_length=200, verbose_name="b2 file id"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="file type"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user attachment",
                "verbose_name_plural": "user attachments",
                "ordering": ["-created_at"],
            },
        ),
    ]
