# Generated by Django 5.2 on 2026-01-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_add_user_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="blood_type",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="blood type"
            ),
        ),
    ]
