# Generated by Django 4.2.7 on 2025-12-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Med",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="medication name"),
                ),
                ("note", models.TextField(blank=True, verbose_name="notes")),
                (
                    "avg_price",
                    models.FloatField(
                        blank=True, null=True, verbose_name="average price"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "medication",
                "verbose_name_plural": "medications",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PatientMed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "med_name",
                    models.CharField(
                        blank=True,
                        help_text="Stored for reference even if med is deleted",
                        max_length=255,
                        verbose_name="medication name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "patient medication",
                "verbose_name_plural": "patient medications",
                "ordering": ["-created_at"],
            },
        ),
    ]
