# Generated by Django 4.2.7 on 2025-12-26 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patientmed",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescribed_meds",
                to=settings.AUTH_USER_MODEL,
                verbose_name="prescribed by",
            ),
        ),
        migrations.AddField(
            model_name="patientmed",
            name="med",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patient_records",
                to="medications.med",
                verbose_name="medication",
            ),
        ),
        migrations.AddField(
            model_name="patientmed",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="patient",
            ),
        ),
        migrations.AddField(
            model_name="med",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_meds",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
    ]
