# Generated by Django 4.2.7 on 2025-12-26 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "systolic",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="systolic pressure"
                    ),
                ),
                (
                    "diastolic",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="diastolic pressure"
                    ),
                ),
                (
                    "o2",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="oxygen saturation"
                    ),
                ),
                (
                    "puls",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="pulse rate"
                    ),
                ),
                (
                    "temp",
                    models.FloatField(
                        blank=True, null=True, verbose_name="temperature"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="weight (kg)"
                    ),
                ),
                (
                    "reading_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reading date"
                    ),
                ),
                (
                    "files",
                    models.JSONField(
                        blank=True, default=list, verbose_name="attached files"
                    ),
                ),
                (
                    "mood",
                    models.CharField(blank=True, max_length=100, verbose_name="mood"),
                ),
                ("note", models.TextField(blank=True, verbose_name="patient note")),
                ("dr_note", models.TextField(blank=True, verbose_name="doctor note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "vital",
                "verbose_name_plural": "vitals",
                "ordering": ["-reading_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BabyVital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puls",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="pulse rate"
                    ),
                ),
                (
                    "systolic",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="systolic pressure"
                    ),
                ),
                (
                    "diastolic",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="diastolic pressure"
                    ),
                ),
                (
                    "o2",
                    models.FloatField(
                        blank=True, null=True, verbose_name="oxygen saturation"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="weight (kg)"
                    ),
                ),
                (
                    "age",
                    models.CharField(blank=True, max_length=50, verbose_name="age"),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "reading_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reading date"
                    ),
                ),
                (
                    "files",
                    models.JSONField(
                        blank=True, default=list, verbose_name="attached files"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="due date"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baby_vitals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "baby vital",
                "verbose_name_plural": "baby vitals",
                "ordering": ["-reading_date", "-created_at"],
            },
        ),
    ]
