# Generated by Django 5.2 on 2025-12-31 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_patientprofile_pregnancy_baby"),
        ("visits", "0002_visit_pregnancy_alter_visit_patient"),
        ("vitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="babyvital",
            name="baby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vitals",
                to="users.baby",
                verbose_name="baby",
            ),
        ),
        migrations.AddField(
            model_name="babyvital",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="baby_vitals",
                to="visits.visit",
                verbose_name="visit",
            ),
        ),
        migrations.AddField(
            model_name="vital",
            name="pregnancy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vitals",
                to="users.pregnancy",
                verbose_name="pregnancy",
            ),
        ),
        migrations.AddField(
            model_name="vital",
            name="visit",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vital",
                to="visits.visit",
                verbose_name="visit",
            ),
        ),
        migrations.AlterField(
            model_name="babyvital",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baby_vitals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="parent (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="vital",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vitals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="patient (deprecated)",
            ),
        ),
    ]
