# Generated by Django 5.2 on 2026-01-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitals", "0002_babyvital_baby_babyvital_visit_vital_pregnancy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vital",
            name="sugar_level",
            field=models.IntegerField(
                blank=True,
                help_text="Blood glucose level in mg/dL",
                null=True,
                verbose_name="blood glucose level",
            ),
        ),
    ]
