# Generated by Django 5.2 on 2026-01-13 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_visitattachment'),
        ('vitals', '0004_add_vital_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField(blank=True, null=True, verbose_name='systolic pressure')),
                ('diastolic', models.IntegerField(blank=True, null=True, verbose_name='diastolic pressure')),
                ('o2', models.IntegerField(blank=True, null=True, verbose_name='oxygen saturation')),
                ('puls', models.IntegerField(blank=True, null=True, verbose_name='pulse rate')),
                ('temp', models.FloatField(blank=True, null=True, verbose_name='temperature')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='weight (kg)')),
                ('sugar_level', models.IntegerField(blank=True, help_text='Blood glucose level in mg/dL', null=True, verbose_name='blood glucose level')),
                ('reading_date', models.DateTimeField(blank=True, null=True, verbose_name='reading date')),
                ('files', models.JSONField(blank=True, default=list, verbose_name='attached files')),
                ('mood', models.CharField(blank=True, max_length=100, verbose_name='mood')),
                ('note', models.TextField(blank=True, verbose_name='patient note')),
                ('dr_note', models.TextField(blank=True, verbose_name='doctor note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_vitals', to=settings.AUTH_USER_MODEL, verbose_name='patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_vitals', to='visits.visit', verbose_name='visit')),
            ],
            options={
                'verbose_name': 'patient vital',
                'verbose_name_plural': 'patient vitals',
                'ordering': ['-reading_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientVitalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='file name')),
                ('file_id', models.CharField(max_length=200, verbose_name='b2 file id')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='file type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_vital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='vitals.patientvital', verbose_name='patient vital')),
            ],
        ),
    ]
