# Generated by Django 4.2.7 on 2025-12-26 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="appointment time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("جاري التأكيد", "جاري التأكيد"),
                            ("مؤكد", "مؤكد"),
                            ("مكتمل", "مكتمل"),
                            ("ملغي", "ملغي"),
                        ],
                        default="جاري التأكيد",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="patient note")),
                (
                    "urgency",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="urgency level"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="clinics.clinic",
                        verbose_name="clinic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "visit",
                "verbose_name_plural": "visits",
                "ordering": ["-time"],
            },
        ),
    ]
