# Generated by Django 5.2 on 2025-12-31 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_patientprofile_pregnancy_baby"),
        ("visits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="pregnancy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to="users.pregnancy",
                verbose_name="pregnancy",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="patient (deprecated)",
            ),
        ),
    ]
