# Generated by Django 5.2 on 2026-01-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0002_visit_pregnancy_alter_visit_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="cancellation_reason",
            field=models.TextField(blank=True, verbose_name="cancellation reason"),
        ),
        migrations.AddField(
            model_name="visit",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="cancelled at"
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="cancelled_by",
            field=models.CharField(
                blank=True,
                help_text="Who cancelled: patient or clinic",
                max_length=20,
                verbose_name="cancelled by",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="previous_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="previous appointment time"
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="rescheduled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="rescheduled at"
            ),
        ),
    ]
