# Generated by Django 4.2.7 on 2026-01-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0003_visit_cancellation_reason_visit_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="recording_url",
            field=models.TextField(blank=True, null=True, verbose_name="recording url"),
        ),
    ]
