# Generated by Django 4.2.7 on 2026-01-09 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0004_visit_recording_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="file name")),
                (
                    "file_id",
                    models.CharField(max_length=200, verbose_name="b2 file id"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="file type"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="visits.visit",
                        verbose_name="visit",
                    ),
                ),
            ],
        ),
    ]
